name: Feature request
description: Propose a new capability or change
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Share the problem first, then the solution.
        Please keep requests aligned with the project scope in README.md.
  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight
      options:
        - label: I searched existing issues
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the change at a high level.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: scope
    attributes:
      label: Scope and impact
      description: What parts of the system would change?
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: What does done look like?
  - type: textarea
    id: out_of_scope
    attributes:
      label: Out of scope
      description: What should not be included?
